import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import * as fs from 'fs';
import * as path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Plugin to inline WASM as base64
const inlineWasmPlugin = {
	name: 'inline-wasm',
	setup(build) {
		build.onResolve({ filter: /sql-wasm\.wasm/ }, (args) => ({
			path: args.path,
			namespace: 'wasm-loader',
		}));

		build.onLoad({ filter: /.*/, namespace: 'wasm-loader' }, () => {
			const wasmPath = path.resolve('node_modules/sql.js/dist/sql-wasm.wasm');
			if (!fs.existsSync(wasmPath)) {
				throw new Error(`WASM file not found: ${wasmPath}`);
			}
			const wasmData = fs.readFileSync(wasmPath);
			const base64Data = wasmData.toString('base64');
			const wasmDataUrl = `data:application/wasm;base64,${base64Data}`;
			return {
				contents: `export default '${wasmDataUrl}';`,
				loader: 'js',
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [inlineWasmPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
