/**
 * Bible book number mappings from actual database
 * Note: Book numbers follow irregular pattern, not simply position * 10
 *
 * Old Testament: 10-460 (39 books)
 * New Testament: 470-730 (27 books)
 */

export const BOOK_MAPPINGS = {
	// Old Testament
	GENESIS: 10,
	EXODUS: 20,
	LEVITICUS: 30,
	NUMBERS: 40,
	DEUTERONOMY: 50,
	JOSHUA: 60,
	JUDGES: 70,
	RUTH: 80,
	FIRST_SAMUEL: 90,
	SECOND_SAMUEL: 100,
	FIRST_KINGS: 110,
	SECOND_KINGS: 120,
	FIRST_CHRONICLES: 130,
	SECOND_CHRONICLES: 140,
	EZRA: 150,
	NEHEMIAH: 160,
	ESTHER: 190,
	JOB: 220,
	PSALMS: 230,
	PROVERBS: 240,
	ECCLESIASTES: 250,
	SONG_OF_SOLOMON: 260,
	ISAIAH: 290,
	JEREMIAH: 300,
	LAMENTATIONS: 310,
	EZEKIEL: 330,
	DANIEL: 340,
	HOSEA: 350,
	JOEL: 360,
	AMOS: 370,
	OBADIAH: 380,
	JONAH: 390,
	MICAH: 400,
	NAHUM: 410,
	HABAKKUK: 420,
	ZEPHANIAH: 430,
	HAGGAI: 440,
	ZECHARIAH: 450,
	MALACHI: 460,

	// New Testament
	MATTHEW: 470,
	MARK: 480,
	LUKE: 490,
	JOHN: 500,
	ACTS: 510,
	ROMANS: 520,
	FIRST_CORINTHIANS: 530,
	SECOND_CORINTHIANS: 540,
	GALATIANS: 550,
	EPHESIANS: 560,
	PHILIPPIANS: 570,
	COLOSSIANS: 580,
	FIRST_THESSALONIANS: 590,
	SECOND_THESSALONIANS: 600,
	FIRST_TIMOTHY: 610,
	SECOND_TIMOTHY: 620,
	TITUS: 630,
	PHILEMON: 640,
	HEBREWS: 650,
	JAMES: 660,
	FIRST_PETER: 670,
	SECOND_PETER: 680,
	FIRST_JOHN: 690,
	SECOND_JOHN: 700,
	THIRD_JOHN: 710,
	JUDE: 720,
	REVELATION: 730,
};

/**
 * Reverse mapping from book_number to constant name
 */
export const BOOK_NUMBER_TO_NAME: Record<number, string> = Object.fromEntries(
	Object.entries(BOOK_MAPPINGS).map(([name, num]) => [num, name])
);

/**
 * Get book number from position (1-66)
 * Genesis (1) -> 10, John (43) -> 430, Revelation (66) -> 660
 */
export function getBookNumberFromPosition(position: number): number {
	return position * 10;
}

/**
 * Get book position from book_number
 * 10 -> 1, 430 -> 43, 660 -> 66
 */
export function getPositionFromBookNumber(bookNumber: number): number {
	return bookNumber / 10;
}

/**
 * List of all OT books with their numbers (positions 1-39)
 */
export const OT_BOOKS = [
	BOOK_MAPPINGS.GENESIS,
	BOOK_MAPPINGS.EXODUS,
	BOOK_MAPPINGS.LEVITICUS,
	BOOK_MAPPINGS.NUMBERS,
	BOOK_MAPPINGS.DEUTERONOMY,
	BOOK_MAPPINGS.JOSHUA,
	BOOK_MAPPINGS.JUDGES,
	BOOK_MAPPINGS.RUTH,
	BOOK_MAPPINGS.FIRST_SAMUEL,
	BOOK_MAPPINGS.SECOND_SAMUEL,
	BOOK_MAPPINGS.FIRST_KINGS,
	BOOK_MAPPINGS.SECOND_KINGS,
	BOOK_MAPPINGS.FIRST_CHRONICLES,
	BOOK_MAPPINGS.SECOND_CHRONICLES,
	BOOK_MAPPINGS.EZRA,
	BOOK_MAPPINGS.NEHEMIAH,
	BOOK_MAPPINGS.ESTHER,
	BOOK_MAPPINGS.JOB,
	BOOK_MAPPINGS.PSALMS,
	BOOK_MAPPINGS.PROVERBS,
	BOOK_MAPPINGS.ECCLESIASTES,
	BOOK_MAPPINGS.ISAIAH,
	BOOK_MAPPINGS.JEREMIAH,
	BOOK_MAPPINGS.LAMENTATIONS,
	BOOK_MAPPINGS.EZEKIEL,
	BOOK_MAPPINGS.DANIEL,
	BOOK_MAPPINGS.HOSEA,
	BOOK_MAPPINGS.JOEL,
	BOOK_MAPPINGS.AMOS,
	BOOK_MAPPINGS.OBADIAH,
	BOOK_MAPPINGS.JONAH,
	BOOK_MAPPINGS.MICAH,
	BOOK_MAPPINGS.NAHUM,
	BOOK_MAPPINGS.HABAKKUK,
	BOOK_MAPPINGS.ZEPHANIAH,
	BOOK_MAPPINGS.HAGGAI,
	BOOK_MAPPINGS.ZECHARIAH,
	BOOK_MAPPINGS.MALACHI,
];

/**
 * List of all NT books with their numbers (positions 40-66)
 */
export const NT_BOOKS = [
	BOOK_MAPPINGS.MATTHEW,
	BOOK_MAPPINGS.MARK,
	BOOK_MAPPINGS.LUKE,
	BOOK_MAPPINGS.JOHN,
	BOOK_MAPPINGS.ACTS,
	BOOK_MAPPINGS.ROMANS,
	BOOK_MAPPINGS.FIRST_CORINTHIANS,
	BOOK_MAPPINGS.SECOND_CORINTHIANS,
	BOOK_MAPPINGS.GALATIANS,
	BOOK_MAPPINGS.EPHESIANS,
	BOOK_MAPPINGS.PHILIPPIANS,
	BOOK_MAPPINGS.COLOSSIANS,
	BOOK_MAPPINGS.FIRST_THESSALONIANS,
	BOOK_MAPPINGS.SECOND_THESSALONIANS,
	BOOK_MAPPINGS.FIRST_TIMOTHY,
	BOOK_MAPPINGS.SECOND_TIMOTHY,
	BOOK_MAPPINGS.TITUS,
	BOOK_MAPPINGS.PHILEMON,
	BOOK_MAPPINGS.HEBREWS,
	BOOK_MAPPINGS.JAMES,
	BOOK_MAPPINGS.FIRST_PETER,
	BOOK_MAPPINGS.SECOND_PETER,
	BOOK_MAPPINGS.FIRST_JOHN,
	BOOK_MAPPINGS.SECOND_JOHN,
	BOOK_MAPPINGS.THIRD_JOHN,
	BOOK_MAPPINGS.JUDE,
	BOOK_MAPPINGS.REVELATION,
];

export const ALL_BOOKS = [...OT_BOOKS, ...NT_BOOKS];
